### PR TITLE
USBSID-Pico support via WebUSB

### PR DESCRIPTION
**Pull request by LouDnl**
Hi @Chordian ,

As promised, here is a first rough implementation of WebUSB support for USBSID-Pico by adding webusb to Hermit's emulator.
My experience is that WebUSB is quite demanding resource wise.

I think that all files needed to be edited for support have been edited, but of course feel free to comment and or request any changes.

LouD

### CODE REVIEW

**Comment by Chordian** [comment]
Looks good and it's now online. Thanks for the contribution. 😊

I also added your credits in 'About' and a few lines in annex tips for URL parameters and SID handlers.

**Comment by LouDnl** [comment]
> Looks good and it's now online. Thanks for the contribution. 😊
> 
> I also added your credits in 'About' and a few lines in annex tips for URL parameters and SID handlers.

Thanks! 🔥

**Comment by LouDnl** [comment]
There is some sort of issue unfortunately, did I miss something?
image

**Comment by Chordian** [comment]
Someone on Facebook tried your SID handler and also got the same error, but after reconnecting the device it worked for him.

**Comment by thomasj** [comment]
Fun to see that my ASID additions to Hermit's got some more use! One note - when I added it I specifically didn't want to change original whitespace of Hermit's, in order to have a simple diff. I notice that the WebUSB additions were done in the same commit as a lot of whitespace fixes which means it is hard to se what is done. Is there any way that these changes can be split up, so that the actual functional change can be reviewed? Otherwise I will try to do that diff manually.

**Comment by LouDnl** [comment]
> Fun to see that my ASID additions to Hermit's got some more use! One note - when I added it I specifically didn't want to change original whitespace of Hermit's, in order to have a simple diff. I notice that the WebUSB additions were done in the same commit as a lot of whitespace fixes which means it is hard to se what is done. Is there any way that these changes can be split up, so that the actual functional change can be reviewed? Otherwise I will try to do that diff manually.

I will see what I can do! Also need to find an issue with notes being cut off with webusb.

**Comment by LouDnl** [comment]
@Chordian @thomasj new pull request made in #33

**Pull request merged**
