### PR TITLE
Added ASID support to playback SID files on hardware

### PR DESCRIPTION
**Pull request by thomasj**
Added ASID support to playback SID files on hardware such as SidStation, TherapSID, Midibox SID and C64 (using Station64). Created by adding functionality to the already existing Hermit handler.

Implements ticket #22

### CODE REVIEW

**Comment by thomasj** [comment]
I tried to have a bunch of comments to make it easier to understand what is going on. Also the UI side of things is pretty basic - could benefit from things such as styled select box and probably other things :)

**Comment by Chordian** [comment]
I also thought about adding it to Hermit's SID handler.

**Comment by thomasj** [comment]
Great! Since I developed on a local web server with other URLs I manually changed a few lines before commit, to adapt to the original. But hopefully it should work also in the official env. Just let me know otherwise!

**Comment by Chordian** [comment]
It looks really good. I'm surprised that you altered Hermit's handler to work both as the original and for ASID at the same time. I would probably have been lazy and duplicated Hermit's JS file.

I hope to merge and adapt it this weekend.

Do you know of a software-only SID player that I can test up against? The only hardware device I have is the SidBlaster Tic Tac and it doesn't have a MIDI interface.

**Comment by thomasj** [comment]
Thanks! Yeah, I had that idea also but realised that it would be much cleaner (and make future bug fixes easier to handle) to make both work from the same file. I haven't tried it myself, but if you have a C64 with a MIDI interface you should be able to run Station64 and test.

**Comment by thomasj** [comment]
You could also do basic verification by running a MIDI monitor app on your computer and check that SysEx messages of size 13-40 is sent about 50 times per second. Then I can validate with real HW.

**Comment by Chordian** [comment]
I'll probably rely on your SID handler working correctly and let you test if it really does. 😉

**Comment by thomasj** [comment]
Sounds good! Just let me know when it is ready and I'll test.

**Comment by Chordian** [comment]
I adapted your code to my localhost version, and it worked fine there because Chrome just claimed MIDI was not available at that point. I styled the MIDI port drop-down to look better and added incompatibility fields in the database.

However, when I uploaded it online and tested it, there were various Javascript errors that broke down the site preventing me from choosing a different SID handler. Something was not working properly regarding the error handling.

I tried a few things such as adding try/catch blocks around the offenders (in asidSendBuffer() and in init() for midiAccessObj) but I kept getting new JS errors online. I had to remove the ASID option for now.

Can you see what needs to be improved to error handling?

**Comment by thomasj** [comment]
I actually watched the site a short while during your upload when you have styled the select box, and after doing a cookie refresh and reload page it seemed to look fine - except that the MIDI ports where not populated. I think you might have had the same issue that prevented me from using styled select: that the current JS code doesn't support adding/removing options during runtime. 
Could you temporarily just put my non-styled version up (i.e as of latest master with #23), and I'll check if that works ok?

**Comment by Chordian** [comment]
Damn, I was afraid the styled select might do that. I'll disable it.

**Comment by Chordian** [comment]
It's unstyled now.

**Comment by thomasj** [comment]
Ok thanks! Since you changed the ID of the select box need to adapt this line to the new ID:
` const select = document.getElementById('midiOutputs');`

**Comment by Chordian** [comment]
I think I did search for all instances of that. I'll check again.

You're right, two lines had rolled back at one point. Updated them again.

**Comment by Chordian** [comment]
I managed to make the error handling stop producing showstopping errors. Now it just shows the alert about MIDI device not found 2-3 times. So I guess it's possible to test it now.

**Comment by thomasj** [comment]
I see some try/catch cases has been added and it is possible that some of them might cause "incorrect" errors. Could these be restored to the original form as well?

**Comment by Chordian** [comment]
I added those to stop the showstopper errors. I can try removing them again, at least so you can see what happens in the console.

**Comment by Chordian** [comment]
They're now removed. As you can see, there are now TypeError exceptions.

**Comment by thomasj** [comment]
It actually works perfectly for me now :) Playing back from my TherapSID-develeoper unit. So maybe there is an issue if no MIDI interfaces are available at all?

**Comment by Chordian** [comment]
Exactly. That's when I get the exception errors. 

Didn't it work for you with the try/catch stuff added?

**Comment by thomasj** [comment]
Nope, with the try-catches added I believed it failed on 
```
// Populate dropdown with available MIDI ports
 outputs.forEach((output, index) => {
```

I'll see if I can try to remove all my MIDI interfaces from the computer to test it.

**Comment by Chordian** [comment]
I fixed it in a more elegant way that didn't require me to edit Hermit's file at all.

In main.js I added this:

`				try {
					SID.unload();
				} catch (err) {}
`

It makes it possible to select a different SID handler even after ASID created exception errors.

**Comment by thomasj** [comment]
Ok, finally removed my MIDI devices (had a bunch of virtual ones that was a bit slow to remove). Anyway, I also get the error now - will try to debug that locally. But first, could you add `asid_enabled = false;` after this line and I'll try again?

`  alert("No MIDI devices found.");`

**Comment by Chordian** [comment]
Added now.

**Comment by thomasj** [comment]
Yes, it seems to work fine for me now - both with and without MIDI devices, nice!

**Comment by Chordian** [comment]
I can live with the exception errors now that I added the try/catch in main.js. 🙂

As long as the users doesn't look in the console, it looks like it's working as intended.

**Comment by thomasj** [comment]
Great!
After having cleared browser cookies etc I now only get an exception in the console if :
 * Selected ASID with no MIDI devices available
 * Pressing Play on a song
When it is all merged to main I can try to come up with a more robust handling of no devices in a future PR.

**Comment by Chordian** [comment]
The changes have been checked in now.

**Pull request merged**
