### PR TITLE
Fix note cutoff and revert all whitespace removal

### PR DESCRIPTION
**Pull request by LouDnl**
Hi @Chordian , this fixes note cutoff for WebUSB and reverts all accidental whitespace removal @thomasj

### CODE REVIEW

**Comment by Chordian** [comment]
It should now be online.

**Comment by LouDnl** [comment]
@thomasj whitespace revert better now?

**Comment by thomasj** [comment]
@LouDnl Looks all good, now very easy to see the changes! And since you added 4-SID support I might do that for ASID too :)

**Comment by LouDnl** [comment]
> @LouDnl Looks all good, now very easy to see the changes! And since you added 4-SID support I might do that for ASID too :)

That would be awesome!

**Comment by LouDnl** [comment]
> @LouDnl Looks all good, now very easy to see the changes! And since you added 4-SID support I might do that for ASID too :)

Adding 4x SID support was easier then I thought, got it running on the usbsid config page. Will do a new pull request as soon as I fix the clicking noise caused by the sid address calculation I made. It sometimes falsely detects more sids then actually in the tune.

**Pull request merged**
